name: Volcamp
description: La première conférence au cœur des volcans d'Auvergne faite pour les passionnés de technologie, de développement et de terroir.
author: Geek&Terroir
keywords: Volcamp, tech conference, conference, auvergne, clermont-fd, Geek&Terroir

url: https://www.volcamp.io

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - CNAME

navigation:
 - title: Programme
   url: /programme/
 - title: Intervenants
   url: /speakers/
 - title: Sponsors
   url: /sponsors/

collections:
  talks:
    output: true

syndication:
  twitter: http://www.twitter.com/volcampio
  github: https://github.com/Volcamp
  linkedin: https://www.linkedin.com/company/volcampio

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-minifier
